Update bt_ci_on_premise.yml to be able to push into another repository obfuscated code
brain-tec/ci_workflows pull request #64
Opened 2024-01-03 22:33 UTC by BT-rmartin

Useful for odoo.sh

2024-01-08 16:00 UTC, BT-sschmid requested changes

2024-01-09 12:28 UTC, BT-sschmid commented on .github/workflows/bt_ci_on_premise.yml
> +          sed -i "s/$CURRENT_REPO/${{ inputs.remote_repo }}/g" .braintec/deploy.yaml
sed would also replace all other occurrences which are a super-string of CURRENT_REPO. 
Instead I'd propose to do 

```
python3 -c 'import sys, yaml; d=yaml.safe_load(open(sys.argv[1])); next(filter(lambda r: r.get("mainrepo"), d["git_repositories"]))["repository"] = sys.argv[2]; print(yaml.safe_dump(d));' deploy.yaml ${{ inputs.remote_repo }}
```

2024-01-10 14:44 UTC, BT-rmartin commented on .github/workflows/bt_ci_on_premise.yml
> +          sed -i "s/$CURRENT_REPO/${{ inputs.remote_repo }}/g" .braintec/deploy.yaml
Changed sed by python script. Your proposed solution wasn't working well as the yaml file is reordered and it was not replacing the content of the file

2024-01-10 14:58 UTC, BT-rmartin commented on .github/workflows/bt_ci_on_premise.yml
> +          ref: odoosh
IMPORTANT! Switch to master once this is going to be merged

2024-01-11 08:41 UTC, BT-sschmid commented on .github/scripts/adapt_remote_deploy_yaml.py
> +
What I meant with my comment, was to not use string replacements at all. 
Although this will work in most cases the cleaner way is to parse the yaml and change the appropriate keys in the parsed dictionary and to dump it again. 

This one-liner is doing exactly this;
```
python3 -c 'import sys, yaml; d=yaml.safe_load(open(sys.argv[1])); next(filter(lambda r: r.get("mainrepo"), d["git_repositories"]))["repository"] = sys.argv[2]; print(yaml.safe_dump(d));' deploy.yaml ${{ inputs.remote_repo }}
```

2024-01-11 11:46 UTC, BT-rmartin commented on .github/scripts/adapt_remote_deploy_yaml.py
> +
Ok done now in this way

2024-01-11 11:46 UTC, BT-rmartin commented on .github/actions/bt_cli_installation/action.yaml
> +        ref: bugfix_pylint_python_version
IMPORTANT! Switch to master once we merge https://github.com/brain-tec/bt-docker/pull/357

2024-01-11 11:47 UTC, BT-rmartin commented on .github/workflows/bt_ci_workflow_code_quality.yml
> +          ref: odoosh
IMPORTANT! Switch to master once we merge this PR

2024-01-11 12:15 UTC, BT-sschmid approved these changes

2024-01-11 14:38 UTC, merged